# -*- coding: utf-8 -*-
"""News.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qTpHnVEAdSxx1l_eFQHGRXGAqDY2P0gV
"""

from bs4 import BeautifulSoup
import requests
import nltk
import re
import pandas as pd
nltk.download('punkt')

df = pd.read_csv("/content/news.csv")
for index, row in df.iterrows():
  url=(row['THE HINDU'])
  url

import pandas as pd

df = pd.read_csv("/content/news.csv")
df1 = df['THE HINDU'].tolist()
url = df['THE HINDU'].tolist()
news= [] 
print (df)

for urls in url:
  paper=  re.findall('^(?:http:\/\/|www\.|https:\/\/)([^\/]+)', urls)
  html_content = requests.get(urls).text
  soup = BeautifulSoup(html_content, "html.parser")

  texts = soup.find_all('h1' and 'p')

  
  for text in texts:
    
    thehindu= text.get_text().strip().replace( "© THG PUBLISHING PVT LTD." , '').replace("Our code of editorial values", "").replace("(", "").replace(")", "")
    
    news = ' '.join(thehindu.split())
    sentance= nltk.sent_tokenize(news)
    
    for s in sentance:
      flag=bool(re.search("\d+""%", s))
      if flag:
        out= {'Paper_Name':[paper],'Article':[s]}    
        print(out)

sample_dict = [
{'Paper_Name': 'www.thehindu.com', 'Article': 'The Samajwadi Party SP-Rashtriya Lok Dal RLD alliance has fielded non-Muslim candidates in all six seats of the district, which has around 41% Muslim population.'},
{'Paper_Name': 'www.thehindu.com', 'Article': 'polls was 60.44% as of 5 p.m., the EC said'},
{'Paper_Name': 'www.thehindu.com', 'Article': 'The final voter turnout figures, which is expected to cross 80%, will come in only after the postal ballots are taken into account,” said Goa Chief Electoral Officer Kunal.'},
{'Paper_Name': 'www.thehindu.com', 'Article': 'The State had recorded an 82.56% turnout during the 2017 elections.'},
{'Paper_Name': 'www.thehindu.com', 'Article': 'In Uttarakhand, turnout for the 70-seat Assembly elections was around 62.5%, according to a statement by the Chief Electoral Officer’s office.'},
{'Paper_Name': 'www.thehindu.com', 'Article': 'In 2017, the Uttarakhand polls had seen 64.72% turnout.'},
{'Paper_Name': 'www.thehindu.com', 'Article': 'In U.P., the 55 seats that went to polls are mostly located in the Rohilkhand region with a substantial population of Muslims, above the State average of 19.5%.'},
{'Paper_Name': 'www.thehindu.com', 'Article': 'In Goa, Chief Minister Pramod Sawant’s constituency Sanquelim saw the highest voter turnout at 89.64% — a jump of nearly five percentage points since the 2017 Assembly election.'},
{'Paper_Name': 'www.thehindu.com', 'Article': 'The lowest turnout 70.2% was recorded in the Benaulim constituency, said Mr. Kunal, adding that the 19 seats in North Goa recorded a turnout of 79.8% while the 21 Assembly seats in South Goa witnessed a voter turnout of 78.15%'},
{'Paper_Name': 'www.thehindu.com', 'Article': 'As of Friday, 95.8% of those eligible to vote had received both doses of the vaccine in Goa, 82.39% in Uttarakhand, 45.6% in Punjab, 44.8% in Manipur and 52% in U.P., he said.'},
{'Paper_Name': 'www.thehindu.com', 'Article': 'Mr. Chandra said the EC also reviewed the weekly positivity rate, which was 0.24% in U.P., 1.01% in Uttarakhand, 2.1% in Punjab, 1.1% in Manipur and 13% in Manipur “because of the New Years’ parties by outsiders”, he said.'},
{'Paper_Name': 'www.thehindu.com', 'Article': 'The announcement of polls came on the day the country’s daily positivity rate was 9.28% and active cases stood at 4.72 lakh, according to a Health and Family Welfare Ministry statement.'},
{'Paper_Name': 'www.thehindu.com', 'Article': 'In terms of caste and community, the sharpest gender gap with respect to the BJP can be seen among the upper caste community where women supported the BJP in even greater proportion than the men 90% as opposed to 83%.'},
{'Paper_Name': 'www.thehindu.com', 'Article': 'In Lokniti’s 2017 post-poll survey, 47% of women had said that they had taken someone’s advice before voting.'},
{'Paper_Name': 'www.thehindu.com', 'Article': 'In this election, only 32% did.'},
{'Paper_Name': 'www.thehindu.com', 'Article': 'It is also important to state that in the survey, women respondents were more likely to consider women candidates as being a very important voting consideration than men 47% vs 35% and yet women weren’t attracted towards the Congress which gave 40% tickets to women candidates.'},
{'Paper_Name': 'www.thehindu.com', 'Article': 'The party lost almost 10% of its vote share from 2017 and was reduced to one seat.'},
{'Paper_Name': 'www.thehindu.com', 'Article': 'Even if 50% of the State’s 19.5% Muslims had voted for the BSP, the Hindu voters, especially the Brahmins, who were unhappy with the BJP would have voted for the BSP, she noted.'},
{'Paper_Name': 'www.thehindu.com', 'Article': 'in its national plan cannot be overstated — it contributes 20% of the party’s current strength in the Lok Sabha.'},
{'Paper_Name': 'www.thehindu.com', 'Article': 'The party\'s own assessment of data from the recent polls show that between the 2017 polls and the one in 2022, Congress, BSP and others lost 15% of vote share, and of this only 2.5% came to the BJP; the rest went to Samajwadi Party and its allies.'},
{'Paper_Name': 'www.thehindu.com', 'Article': 'About 110 seats were lost with less than 10% of votes polled, of these 68 were won by the BJP and 33 by SP and its allies, a situation that is worrisome and requires remedy.'},
{'Paper_Name': 'www.thehindu.com', 'Article': 'This was our first Assembly election in Uttarakhand and we got 3.8% of votes.'},
{'Paper_Name': 'www.thehindu.com', 'Article': 'He secured 51.5% vote percentage, but he was made to lose by EVMs,” he said.'},
{'Paper_Name': 'www.thehindu.com', 'Article': 'Across the 17 advanced economies we surveyed in 2021, a median of 61% say that their country is more divided than before the outbreak’.'},
{'Paper_Name': 'www.thehindu.com', 'Article': 'Currently lodged in jail, SP’s founding member won the Rampur constituency by securing almost 60% of the votes.'},
{'Paper_Name': 'www.thehindu.com', 'Article': 'Suheldev Bharatiya Samaj Party SBSP chief Om Prakash Rajbhar registered a victory in Zahoorabad constituency, winning over 46% votes.'},
{'Paper_Name': 'www.thehindu.com', 'Article': 'Congress State President Ajay Kumar Lallu contested from Tamukhi Raj and could only secure 14.78% votes in the constituency.'},
{'Paper_Name': 'www.thehindu.com', 'Article': 'Data further indicates that for 12%, removing the present government was what determined their vote.'},
{'Paper_Name': 'www.thehindu.com', 'Article': 'The Ram Mandir issue, which was believed to set the poll narrative in the State, found no resonance, with a mere 2% stating this as a voting issue.'},
{'Paper_Name': 'www.thehindu.com', 'Article': 'When offered specific options, from all the issue options that were read out to voters one by one, inflation and development 74% each followed by unemployment 71% emerged to be important issues Table 2.'},
{'Paper_Name': 'www.thehindu.com', 'Article': 'The issue of stray cattle, which became a key talking point during the campaign, was important for 60%.'},
{'Paper_Name': 'www.thehindu.com', 'Article': '‘Development’ did make a huge difference: BJP secured 57% of votes of those for whom development was the single largest voting issue, SP+ was able to attract a quarter 26% of such voters.'}
]

import csv

col_name=["Paper_Name","Article"]
with open("export.csv", 'w') as csvFile:
        wr = csv.DictWriter(csvFile, fieldnames=col_name)
        wr.writeheader()
        for ele in sample_dict:
            wr.writerow(ele)

df = pd.read_csv('export.csv')
df

df.all()

"""**SENTIMENT ANALYSIS**"""

df["Article"]

pip install textblob

from textblob import TextBlob
textblob_sentiment=[]
for s in df["Article"]:
    txt= TextBlob(s)
    a= txt.sentiment.polarity
    b= txt.sentiment.subjectivity
    textblob_sentiment.append([s,a,b])

df_textblob = pd.DataFrame(textblob_sentiment, columns =['Sentence', 'Polarity', 'Subjectivity'])

df_textblob

df_textblob.info()

pip install -U statsmodels

import seaborn as sns
import matplotlib.pyplot as plt
sns.displot(df_textblob["Polarity"], height= 5, aspect=1.8)
plt.xlabel("Sentence Polarity (Textblob)")

sns.displot(df_textblob["Subjectivity"], height= 5, aspect=1.8)
plt.xlabel("Sentence Subjectivity (Textblob)")

"""Word Frequency and Word Cloud"""

#Creating the tokenizer
tokenizer = nltk.tokenize.RegexpTokenizer('\w+|\$[\d\.]+|\S+')

df_textblob["Sentence"] = df_textblob["Sentence"].values.astype(str)

len(df_textblob["Sentence"])

#Tokenizing the text
tokens = tokenizer.tokenize(df_textblob["Sentence"][0]) #change integer value for different news
tokens

len(tokens)

words = []
# Looping through the tokens and make them lower case
for word in tokens:
    words.append(word.lower())

import nltk
nltk.download('stopwords')
stopwords = nltk.corpus.stopwords.words('english')

words_new=[]
for word in words:
    if word not in stopwords:
        words_new.append(word)

len(words_new)

print(words_new[0:10])

#The frequency distribution of the words
freq_dist = nltk.FreqDist(words_new)

#Frequency Distribution Plot
plt.subplots(figsize=(16,10))
freq_dist.plot(20)

#converting into string
res=' '.join([i for i in words_new if not i.isdigit()])

from wordcloud import WordCloud 
plt.subplots(figsize=(16,10))
wordcloud = WordCloud(
                          background_color='black',
                          max_words=100,
                          width=1400,
                          height=1200
                         ).generate(res)
plt.imshow(wordcloud)
plt.title('NEWS ARTICLE (100 words)')
plt.axis('off')
plt.show()